site_name: tsdf
site_url: https://biomarkersparkinson.github.io/tsdf/

repo_url: https://github.com/biomarkersParkinson/tsdf/
edit_uri: 'blob/main/docs/'

plugins:
  - mkdocs-jupyter

theme: readthedocs

nav:
  - Introduction: index.md
  - Installation: installation.md

  - The format:
    - TSDF metadata fields: tsdf_fields_table.md

  - Usage:
    - Basic reading and writing (numpy): basic_reading_and_writing_numpy.ipynb
    - Basic reading and writing (pandas): basic_reading_and_writing_pandas.ipynb
    - Writing data from scratch: writing_data_from_scratch.ipynb
    - Converting legacy data: converting_legacy_data.ipynb
    - Validating files: validating_files.ipynb

  - About:
    - Contact: contact.md

markdown_extensions:
  - extra
