site_name: tsdf
site_url: https://biomarkersparkinson.github.io/tsdf/

repo_url: https://github.com/biomarkersParkinson/tsdf/
edit_uri: 'blob/main/docs/'

plugins:
  - mkdocs-jupyter

theme: readthedocs

nav:
  - Introduction: index.md
  - TSDF fields: tsdf_fields_table.md
  - Installation: installation.md
  - Example: processing_example.ipynb
  - Usage: usage.ipynb
  - Contact: contact.md
