name: fair-software

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: fair-software/howfairis-github-action@0.2.1
        name: Measure compliance with fair-software.eu recommendations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYCHARM_HOSTED: "Trick colorama into displaying colored output"
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
