# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Build the docs
      run: |
        poetry run mkdocs build
    - name: Prepare for deploying
      run: |
        git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Deploy the docs
      run: |
        poetry run mkdocs gh-deploy

    #     poetry run coverage xml
    # - name: Upload coverage
    #   if: matrix.python-version == 3.9
    #   uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }} #required
    #     file: ./coverage.xml #optional
    #     flags: unittests #optional
    #     name: codecov-umbrella #optional
    #     yml: ./codecov.yml #optional